cc_library (
  name = "net",
  srcs = ["net.cpp"],
  hdrs = ["promise/net.hpp"],
  deps = ["//examples/events:events", "//promise:promise"],
  copts = ["-std=c++14"],
  includes = ["."],
  visibility = ["//examples:__subpackages__"],
)
